In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LinearRegression,LogisticRegression

In [2]:
data=pd.read_csv('loan_data.csv')
data

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [3]:
from sklearn.model_selection import train_test_split


data = pd.read_csv("loan_data.csv")



train, test = train_test_split(
    data,
    test_size=0.2,
    random_state=42
)


train.to_csv("data_train.csv", index=False)
test.to_csv("data_test.csv", index=False)

In [4]:
data=pd.read_csv('data_train.csv')
data

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,34.0,female,Bachelor,97265.0,11,MORTGAGE,15000.0,PERSONAL,12.73,0.15,9.0,631,No,0
1,25.0,male,High School,72953.0,3,RENT,12000.0,VENTURE,11.86,0.16,4.0,659,Yes,0
2,41.0,female,Master,322597.0,18,MORTGAGE,24000.0,PERSONAL,10.37,0.07,11.0,683,Yes,0
3,27.0,male,Associate,94232.0,4,RENT,9600.0,EDUCATION,17.14,0.10,7.0,641,No,0
4,27.0,male,Master,84873.0,7,RENT,7059.0,HOMEIMPROVEMENT,12.97,0.08,3.0,706,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35995,26.0,male,High School,88451.0,6,MORTGAGE,10625.0,EDUCATION,6.03,0.12,4.0,559,Yes,0
35996,25.0,female,High School,34772.0,3,MORTGAGE,5876.0,HOMEIMPROVEMENT,11.69,0.17,4.0,647,No,1
35997,33.0,female,Associate,58317.0,9,MORTGAGE,10707.0,VENTURE,10.74,0.18,9.0,652,Yes,0
35998,26.0,male,Master,178602.0,6,RENT,20000.0,DEBTCONSOLIDATION,17.99,0.11,3.0,604,No,1
35999,26.0,female,High School,210894.0,4,MORTGAGE,15000.0,PERSONAL,11.01,0.07,3.0,664,Yes,0

In [5]:
x_reg=data[['person_age','person_gender','person_education', 'person_income',
       'person_emp_exp', 'person_home_ownership', 'loan_intent',
       'loan_int_rate','cb_person_cred_hist_length',
       'credit_score', 'previous_loan_defaults_on_file']]
y_reg=data[['loan_amnt']]
y_class=data[['loan_status']]

In [6]:
x_reg

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_intent,loan_int_rate,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file
0,34.0,female,Bachelor,97265.0,11,MORTGAGE,PERSONAL,12.73,9.0,631,No
1,25.0,male,High School,72953.0,3,RENT,VENTURE,11.86,4.0,659,Yes
2,41.0,female,Master,322597.0,18,MORTGAGE,PERSONAL,10.37,11.0,683,Yes
3,27.0,male,Associate,94232.0,4,RENT,EDUCATION,17.14,7.0,641,No
4,27.0,male,Master,84873.0,7,RENT,HOMEIMPROVEMENT,12.97,3.0,706,Yes
...,...,...,...,...,...,...,...,...,...,...,...
35995,26.0,male,High School,88451.0,6,MORTGAGE,EDUCATION,6.03,4.0,559,Yes
35996,25.0,female,High School,34772.0,3,MORTGAGE,HOMEIMPROVEMENT,11.69,4.0,647,No
35997,33.0,female,Associate,58317.0,9,MORTGAGE,VENTURE,10.74,9.0,652,Yes
35998,26.0,male,Master,178602.0,6,RENT,DEBTCONSOLIDATION,17.99,3.0,604,No
35999,26.0,female,High School,210894.0,4,MORTGAGE,PERSONAL,11.01,3.0,664,Yes

In [7]:
x_reg=pd.get_dummies(x_reg,columns=['person_gender','person_home_ownership','loan_intent'],dtype=int)
x_reg

,person_age,person_education,person_income,person_emp_exp,loan_int_rate,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,person_gender_female,person_gender_male,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,34.0,Bachelor,97265.0,11,12.73,9.0,631,No,1,0,1,0,0,0,0,0,0,0,1,0
1,25.0,High School,72953.0,3,11.86,4.0,659,Yes,0,1,0,0,0,1,0,0,0,0,0,1
2,41.0,Master,322597.0,18,10.37,11.0,683,Yes,1,0,1,0,0,0,0,0,0,0,1,0
3,27.0,Associate,94232.0,4,17.14,7.0,641,No,0,1,0,0,0,1,0,1,0,0,0,0
4,27.0,Master,84873.0,7,12.97,3.0,706,Yes,0,1,0,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35995,26.0,High School,88451.0,6,6.03,4.0,559,Yes,0,1,1,0,0,0,0,1,0,0,0,0
35996,25.0,High School,34772.0,3,11.69,4.0,647,No,1,0,1,0,0,0,0,0,1,0,0,0
35997,33.0,Associate,58317.0,9,10.74,9.0,652,Yes,1,0,1,0,0,0,0,0,0,0,0,1
35998,26.0,Master,178602.0,6,17.99,3.0,604,No,0,1,0,0,0,1,1,0,0,0,0,0
35999,26.0,High School,210894.0,4,11.01,3.0,664,Yes,1,0,1,0,0,0,0,0,0,0,1,0

In [8]:
education_map={'Associate':4, 'Bachelor':1, 'Doctorate':3, 'High School':0, 'Master':2}
x_reg['person_education']=x_reg['person_education'].map(education_map)
x_reg

,person_age,person_education,person_income,person_emp_exp,loan_int_rate,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,person_gender_female,person_gender_male,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,34.0,1,97265.0,11,12.73,9.0,631,No,1,0,1,0,0,0,0,0,0,0,1,0
1,25.0,0,72953.0,3,11.86,4.0,659,Yes,0,1,0,0,0,1,0,0,0,0,0,1
2,41.0,2,322597.0,18,10.37,11.0,683,Yes,1,0,1,0,0,0,0,0,0,0,1,0
3,27.0,4,94232.0,4,17.14,7.0,641,No,0,1,0,0,0,1,0,1,0,0,0,0
4,27.0,2,84873.0,7,12.97,3.0,706,Yes,0,1,0,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35995,26.0,0,88451.0,6,6.03,4.0,559,Yes,0,1,1,0,0,0,0,1,0,0,0,0
35996,25.0,0,34772.0,3,11.69,4.0,647,No,1,0,1,0,0,0,0,0,1,0,0,0
35997,33.0,4,58317.0,9,10.74,9.0,652,Yes,1,0,1,0,0,0,0,0,0,0,0,1
35998,26.0,2,178602.0,6,17.99,3.0,604,No,0,1,0,0,0,1,1,0,0,0,0,0
35999,26.0,0,210894.0,4,11.01,3.0,664,Yes,1,0,1,0,0,0,0,0,0,0,1,0

In [9]:
np.unique(x_reg['person_education'])

array([0, 1, 2, 3, 4], dtype=int64)

In [10]:
previous_loan_defaults_on_file_map={'No':0,'Yes':1}
x_reg['previous_loan_defaults_on_file']=x_reg['previous_loan_defaults_on_file'].map(previous_loan_defaults_on_file_map)
x_reg

,person_age,person_education,person_income,person_emp_exp,loan_int_rate,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,person_gender_female,person_gender_male,person_home_ownership_MORTGAGE,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_DEBTCONSOLIDATION,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,34.0,1,97265.0,11,12.73,9.0,631,0,1,0,1,0,0,0,0,0,0,0,1,0
1,25.0,0,72953.0,3,11.86,4.0,659,1,0,1,0,0,0,1,0,0,0,0,0,1
2,41.0,2,322597.0,18,10.37,11.0,683,1,1,0,1,0,0,0,0,0,0,0,1,0
3,27.0,4,94232.0,4,17.14,7.0,641,0,0,1,0,0,0,1,0,1,0,0,0,0
4,27.0,2,84873.0,7,12.97,3.0,706,1,0,1,0,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35995,26.0,0,88451.0,6,6.03,4.0,559,1,0,1,1,0,0,0,0,1,0,0,0,0
35996,25.0,0,34772.0,3,11.69,4.0,647,0,1,0,1,0,0,0,0,0,1,0,0,0
35997,33.0,4,58317.0,9,10.74,9.0,652,1,1,0,1,0,0,0,0,0,0,0,0,1
35998,26.0,2,178602.0,6,17.99,3.0,604,0,0,1,0,0,0,1,1,0,0,0,0,0
35999,26.0,0,210894.0,4,11.01,3.0,664,1,1,0,1,0,0,0,0,0,0,0,1,0

In [11]:
model_reg=LinearRegression()
model_reg.fit(x_reg,y_reg)

LinearRegression()

In [12]:
y_reg

       loan_amnt
0        15000.0
1        12000.0
2        24000.0
3         9600.0
4         7059.0
...          ...
35995    10625.0
35996     5876.0
35997    10707.0
35998    20000.0
35999    15000.0

[36000 rows x 1 columns]

In [13]:
model_class=LogisticRegression()
model_class.fit(x_reg,y_class)

C:\Users\zohre\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\zohre\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [14]:
x_test=[[38.0,"female","High School",123335.0,16,"MORTGAGE","EDUCATION",14.06,11.0,640,"No"]]
x_test=pd.DataFrame(x_test,columns=['person_age','person_gender','person_education', 'person_income',
       'person_emp_exp', 'person_home_ownership', 'loan_intent',
       'loan_int_rate','cb_person_cred_hist_length',
       'credit_score', 'previous_loan_defaults_on_file'])

education_map={'Associate':4, 'Bachelor':1, 'Doctorate':3, 'High School':0, 'Master':2}
x_test['person_education']=x_test['person_education'].map(education_map)

previous_loan_defaults_on_file_map={'No':0,'Yes':1}
x_test['previous_loan_defaults_on_file']=x_test['previous_loan_defaults_on_file'].map(previous_loan_defaults_on_file_map)

#-------------------------
# مشخص کردن همه حالت‌های ممکن
# -------------------------

x_test["person_gender"] = pd.Categorical(
    x_test["person_gender"],
    categories=["female", "male"]
)

x_test["person_home_ownership"] = pd.Categorical(
    x_test["person_home_ownership"],
    categories=["MORTGAGE", "OTHER", "OWN", "RENT"]
)

x_test["loan_intent"] = pd.Categorical(
    x_test["loan_intent"],
    categories=[
        "DEBTCONSOLIDATION",
        "EDUCATION",
        "HOMEIMPROVEMENT",
        "MEDICAL",
        "PERSONAL",
        "VENTURE"
    ]
)


# -------------------------
# One Hot Encoding
# -------------------------

x_test = pd.get_dummies(
    x_test,
    columns=[
        "person_gender",
        "person_home_ownership",
        "loan_intent"
    ],
    dtype=int
)

print(x_test)

   person_age  person_education  person_income  person_emp_exp  loan_int_rate  \
0        38.0                 0       123335.0              16          14.06

   cb_person_cred_hist_length  credit_score  previous_loan_defaults_on_file  \
0                        11.0           640                               0

   person_gender_female  person_gender_male  person_home_ownership_MORTGAGE  \
0                     1                   0                               1

   person_home_ownership_OTHER  person_home_ownership_OWN  \
0                            0                          0

   person_home_ownership_RENT  loan_intent_DEBTCONSOLIDATION  \
0                           0                              0

   loan_intent_EDUCATION  loan_intent_HOMEIMPROVEMENT  loan_intent_MEDICAL  \
0                      1                            0                    0

   loan_intent_PERSONAL  loan_intent_VENTURE
0                     0                    0